services:
  broker:
    image: apache/kafka:latest
    hostname: cf-broker
    container_name: cf-broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://cf-broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@cf-broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  
  fake-stream: 
    image: ubuntu
    container_name: cf-fake-stream
    hostname: cf-fake-stream
    ports: 
      - '7777:7777'
    volumes:
      - ./fake-stream:/opt/fake-stream

  spark-clean:
    image: apache/spark:3.4.4
    container_name: cf-spark-clean
    hostname: cf-spark-clean
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"  # UI Spark Web
    volumes:
      - ./spark-app:/opt/spark-app
    command: sleep infinity

  spark-flatten:
    image: apache/spark:3.4.4
    container_name: cf-spark-flatten
    hostname: cf-spark-flatten
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4041:4041"  # UI Spark Web
    volumes:
      - ./spark-app:/opt/spark-app
      - ./spark-flatten/ivy-cache:/home/spark/.ivy2 
      - ./spark-flatten/conf:/opt/spark/conf/
    command: sleep infinity

  spark-transform:
    image: apache/spark:3.4.4
    container_name: cf-spark-transform
    hostname: cf-spark-transform
    environment:
      - SPARK_MODE=master
    ports:
      - "4042:4042"  # UI Spark Web
    volumes:
      - ./spark-app:/opt/spark-app
      - ./spark-transform/conf:/opt/spark/conf/
      - ./spark-flatten/ivy-cache:/home/spark/.ivy2 
    command: sleep infinity

  superset:
    image: apache/superset:latest
    container_name: cf-superset
    hostname: cf-superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: mysecret
    # command: superset fab create-admin --username admin --password admin --firstname Admin --lastname User --email admin@admin.com

  grafana:
    image: grafana/grafana:latest
    container_name: cf-grafana
    hostname: cf-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_ANONYMOUS_ORG_ID: 1
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - clickhouse
  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: cf-clickhouse
    hostname: cf-clickhouse
    environment:
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: root
      CLICKHOUSE_DB: default
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data:
  grafana-data:
