version: '3.8'

services:
  broker:
    image: apache/kafka:latest
    hostname: cf-broker
    container_name: cf-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://cf-broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@cf-broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    networks:
      - data_network
  spark-bronze:
    image: bitnami/spark:3.4.3
    container_name: spark-bronze
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4040:4040"  # UI Spark Web
    volumes:
      - ./spark-app:/opt/spark-app
    command: sleep infinity
    networks:
      - data_network

  spark-cleaned:
    image: bitnami/spark:3.4.3
    container_name: spark-cleaned
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4042:4040"  # UI Spark Web
    volumes:
      - ./spark-cleaned:/opt/spark-cleaned
    command: sleep infinity
    networks:
      - data_network
  spark-transform:
    image: bitnami/spark:3.4.3
    container_name: spark-transform
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4041:4040"  # UI Spark Web
    volumes:
      - ./spark-transform:/opt/spark-transform
    command: sleep infinity
    networks:
      - data_network
  spark-clickhouse:
    image: bitnami/spark:3.4.3
    container_name: spark-clickhouse
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4045:4040"  # UI Spark Web
    volumes:
      - ./spark-clickhouse:/opt/spark-clickhouse
    command: sleep infinity
    networks:
      - data_network
  

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9049:9000"   # S3 API
      - "9050:9001"   # Web UI
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - data_network
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: cf-clickhouse
    hostname: cf-clickhouse
    environment:
      HOME: /home/clickhouse
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: root
      CLICKHOUSE_DB: default
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/home/clickhouse/
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - data_network
  
volumes:
  clickhouse-data:
  grafana-data:
  minio_data:
  superset_home:
  metastore-db:
  trino-data:
  mysql-data:

networks:
  data_network:
    driver: bridge

