version: '3.8'

services:
  broker:
    image: apache/kafka:latest
    hostname: cf-broker
    container_name: cf-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://cf-broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@cf-broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  spark-bronze:
    image: bitnami/spark:3.4.3
    container_name: spark-bronze
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4040:4040"  # UI Spark Web
    volumes:
      - ./spark-app:/opt/spark-app
    command: sleep infinity

  spark-cleaned:
    image: bitnami/spark:3.4.3
    container_name: spark-cleaned
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4042:4040"  # UI Spark Web
    volumes:
      - ./spark-cleaned:/opt/spark-cleaned
      - ./spark-conf:/opt/bitnami/spark/conf
    command: sleep infinity
  spark-transform:
    image: bitnami/spark:3.4.3
    container_name: spark-transform
    environment:
      - SPARK_MODE=master
      - HOME=/opt/spark/work-dir
    ports:
      - "4041:4040"  # UI Spark Web
    volumes:
      - ./spark-transform:/opt/spark-transform
    command: sleep infinity


  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9049:9000"   # S3 API
      - "9050:9001"   # Web UI
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  metastore_db:
    image: postgres:11
    container_name: metastore_db
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - ./postgresscripts:/docker-entrypoint-initdb.d
    

  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    
    depends_on:
      - metastore_db
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/9083"


volumes:
  clickhouse-data:
  grafana-data:
  minio_data:
  superset_home:
  metastore-db:
  trino-data:
  hive-metastore-postgresql: